"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Warrior_1 = require("./Warrior");
const Mage_1 = require("./Mage");
const Weapon_1 = require("./Weapon");
const Spell_1 = require("./Spell");
const Party_1 = require("./Party");
const weapon1 = new Weapon_1.Weapon("Longsword", 120);
const weapon2 = new Weapon_1.Weapon("Spear", 100);
const spell1 = new Spell_1.Spell("Relive", 0, 100);
const spell2 = new Spell_1.Spell("Fire Ball", 50, 20);
const mage1 = new Mage_1.Mage("Gandalf", 50, 95, 300, spell2);
const mage2 = new Mage_1.Mage("Clóvis", 10, 80, 200, spell1);
const warrior1 = new Warrior_1.Warrior("Jon Snow", 10, 200, 150, weapon1);
const warrior2 = new Warrior_1.Warrior("Grey Worm", 20, 230, 120, weapon2);
const party1 = new Party_1.Party("Os espanta priquito");
party1.addMember(warrior1);
party1.addMember(warrior2);
party1.addMember(mage1);
party1.addMember(mage2);
party1.showMembers();
console.log("====================================");
console.log("====================================");
warrior1.showInfo();
console.log("====================================");
warrior2.showInfo();
console.log("====================================");
mage1.showInfo();
console.log("====================================");
mage2.showInfo();
console.log("====================================");
console.log("====================================");
warrior1.attack();
console.log("====================================");
warrior2.attack();
console.log("====================================");
mage1.castSpell();
console.log("====================================");
mage2.castSpell();
console.log("====================================");
warrior1.takeDamage(50);
console.log("====================================");
warrior1.setLevel(15);
warrior1.showInfo();
console.log("====================================");
console.log("====================================");
party1.removeMember(mage1);
party1.showMembers();
